name: dart_task_queue
description: "A powerful and flexible task queue implementation for Dart applications"
version: 1.0.1
repository: https://github.com/altaysakarya/dart_task_queue

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
